language: go
sudo: false

services:
  - mongodb

go:
  - 1.14.x
  - 1.15.x
  - 1.16
  - tip

env:
  global:
    - GO111MODULE=on
    - MONGODB_TEST_CXN=localhost
  matrix:
    - FIX_TEST=
    - FIX_TEST=fix40
    - FIX_TEST=fix41
    - FIX_TEST=fix42
    - FIX_TEST=fix43
    - FIX_TEST=fix44
    - FIX_TEST=fix50
    - FIX_TEST=fix50sp1
    - FIX_TEST=fix50sp2

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - go mod download

script: make generate; if [ -z "$FIX_TEST" ]; then make build; make; else make build_accept; make $FIX_TEST; fi
